CREATE TABLE "Model"
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Model"
            PRIMARY KEY,
    model_name TEXT,
    mark       INTEGER
        CONSTRAINT "FK_Model_Mark_mark"
            REFERENCES "Mark"
            ON DELETE RESTRICT,
    year       TIMESTAMP NOT NULL
);

CREATE INDEX "IX_Model_mark"
    ON "Model" (mark);