CREATE TABLE "Delivery"
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Delivery"
            PRIMARY KEY,
    car     INTEGER
        CONSTRAINT "FK_Delivery_Car_car"
            REFERENCES "Car"
            ON DELETE RESTRICT,
    address INTEGER
        CONSTRAINT "FK_Delivery_Address_address"
            REFERENCES "Address"
            ON DELETE RESTRICT,
    courier INTEGER
        CONSTRAINT "FK_Delivery_Staff_courier"
            REFERENCES "Staff"
            ON DELETE RESTRICT
);

CREATE INDEX "IX_Delivery_address"
    ON "Delivery" (address);

CREATE INDEX "IX_Delivery_car"
    ON "Delivery" (car);

CREATE INDEX "IX_Delivery_courier"
    ON "Delivery" (courier);