CREATE TABLE "Staff"
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Staff"
            PRIMARY KEY,
    first_name      TEXT,
    last_name       TEXT,
    patronymic      TEXT,
    passport_serial TEXT,
    passport_number TEXT,
    phone           TEXT,
    inn             TEXT,
    snils           TEXT,
    crm_user        TEXT
        CONSTRAINT "FK_Staff_AspNetUsers_crm_user"
            REFERENCES "AspNetUsers"
            ON DELETE RESTRICT
);

CREATE INDEX "IX_Staff_crm_user"
    ON "Staff" (crm_user);