CREATE TABLE "Factory"
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Factory"
            PRIMARY KEY,
    name            TEXT,
    address         INTEGER
        CONSTRAINT "FK_Factory_Address_address"
            REFERENCES "Address"
            ON DELETE RESTRICT,
    foundation_date TIMESTAMP NOT NULL
);

CREATE INDEX "IX_Factory_address"
    ON "Factory" (address);
