CREATE TABLE "Car"
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Car"
            PRIMARY KEY,
    serial     TEXT,
    region     TEXT,
    mark_model INTEGER
        CONSTRAINT "FK_Car_Model_mark_model"
            REFERENCES "Model"
            ON DELETE RESTRICT
);

CREATE INDEX "IX_Car_mark_model"
    ON "Car" (mark_model);
