CREATE TABLE "GoodInOffer"
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_GoodInOffer"
            PRIMARY KEY,
    good  INTEGER
        CONSTRAINT "FK_GoodInOffer_Good_good"
            REFERENCES "Good"
            ON DELETE RESTRICT,
    offer INTEGER
        CONSTRAINT "FK_GoodInOffer_Offer_offer"
            REFERENCES "Offer"
            ON DELETE RESTRICT,
    count INTEGER NOT NULL
);

CREATE INDEX "IX_GoodInOffer_good"
    ON "GoodInOffer" (good);

CREATE INDEX "IX_GoodInOffer_offer"
    ON "GoodInOffer" (offer);