CREATE TABLE "Store"
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Store"
            PRIMARY KEY,
    name            TEXT,
    address         INTEGER
        CONSTRAINT "FK_Store_Address_address"
            REFERENCES "Address"
            ON DELETE RESTRICT,
    foundation_date TIMESTAMP NOT NULL
);

CREATE INDEX "IX_Store_address"
    ON "Store" (address);


