CREATE TABLE "Buyer"
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Buyer"
            PRIMARY KEY,
    first_name TEXT,
    last_name  TEXT,
    patronymic TEXT,
    email      TEXT,
    phone      TEXT,
    crm_user   TEXT
        CONSTRAINT "FK_Buyer_AspNetUsers_crm_user"
            REFERENCES "AspNetUsers"
            ON DELETE RESTRICT
);

CREATE INDEX "IX_Buyer_crm_user"
    ON "Buyer" (crm_user);