CREATE TABLE "Good"
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Good"
            PRIMARY KEY,
    name        TEXT    NOT NULL,
    description TEXT    NOT NULL,
    good_type   INTEGER
        CONSTRAINT "FK_Good_GoodType_good_type"
            REFERENCES "GoodType"
            ON DELETE RESTRICT,
    factory     INTEGER
        CONSTRAINT "FK_Good_Factory_factory"
            REFERENCES "Factory"
            ON DELETE RESTRICT,
    price       NUMERIC NOT NULL
);

CREATE INDEX "IX_Good_factory"
    ON "Good" (factory);

CREATE INDEX "IX_Good_good_type"
    ON "Good" (good_type);
