CREATE TABLE "Offer"
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Offer"
            PRIMARY KEY,
    code     TEXT,
    buyer    INTEGER
        CONSTRAINT "FK_Offer_Buyer_buyer"
            REFERENCES "Buyer"
            ON DELETE RESTRICT,
    seller   INTEGER
        CONSTRAINT "FK_Offer_Staff_seller"
            REFERENCES "Staff"
            ON DELETE RESTRICT,
    store    INTEGER
        CONSTRAINT "FK_Offer_Store_store"
            REFERENCES "Store"
            ON DELETE RESTRICT,
    delivery INTEGER
        CONSTRAINT "FK_Offer_Delivery_delivery"
            REFERENCES "Delivery"
            ON DELETE RESTRICT,
    sum      NUMERIC NOT NULL
);

CREATE INDEX "IX_Offer_buyer"
    ON "Offer" (buyer);

CREATE INDEX "IX_Offer_delivery"
    ON "Offer" (delivery);

CREATE INDEX "IX_Offer_seller"
    ON "Offer" (seller);

CREATE INDEX "IX_Offer_store"
    ON "Offer" (store);
