CREATE TABLE "AspNetRoleClaims"
(
    "Id"         INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_AspNetRoleClaims"
            PRIMARY KEY,
    "RoleId"     TEXT NOT NULL
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
            REFERENCES "AspNetRoles"
            ON DELETE CASCADE,
    "ClaimType"  TEXT,
    "ClaimValue" TEXT
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId"
    ON "AspNetRoleClaims" ("RoleId");