INSERT INTO "User"( id, login,password,creation_date,last_login,active,)
VALUES
  (1, 'admin','admin','',NULL,'TRUE'),
  (2, 'askuzovatkina','askuzovatkina','',NULL,'TRUE'),
  (3, 'amotozov','amotozov','',NULL,'TRUE'),
  (4, 'yklimova','yklimova','',NULL,'TRUE'),
  (5, 'yavakov','yavakov','',NULL,'TRUE'),
  (6, 'ezelencova','ezelencova','',NULL,'TRUE'),
  (7, 'sberdov','sberdov','',NULL,'TRUE'),
  (8, 'afedotova','afedotova','',NULL,'TRUE'),
  (9, 'akozlov','akozlov','',NULL,'TRUE'),
  (10, 'promanov','promanov','',NULL,'TRUE'),
  (11, 'bbelov','bbelov','',NULL,'TRUE'),
  (12, 'vpetrov','vpetrov','',NULL,'TRUE'),
  (13, 'ibutov','ibutov','',NULL,'TRUE'),
  (14, 'rarkhipov','rarkhipov','',NULL,'TRUE'),
  (15, 'malexandr','malexandr','',NULL,'TRUE'),
  (16, 'episarenko','episarenko','',NULL,'TRUE'),
  (17, 'mbarabanova','mbarabanova','',NULL,'TRUE'),
  (18, 'agolceva','agolceva','',NULL,'TRUE'),
  (19, 'ahapersky','ahapersky','',NULL,'TRUE'),
  (20, 'sgibson','sgibson','',NULL,'TRUE');