version: '3.7'

services:
  app:
    container_name: micrm-app-central
    image: rienelmot24/micrm-app
    ports:
      - 80:80
    environment:
      - MICRM_DB_ADDRESS=db
      - SUBSCRIPTION_DB=db
      - SHOULD_INIT_DB=true
    depends_on:
      - db

  db:
    container_name: micrm-db-central
    image: rienelmot24/micrm-db
    ports:
      - 5432:5432
    command: ["-c", "wal_level=logical",  "-c", "max_connections=500"]

  # MODELLING DISTRIBUTED SYSTEM (CREATING SYSTEM IN MOSCOW REGION)
  # app-msk:
  #   container_name: micrm-app-msk
  #   image: micrm-app
  #   ports:
  #     - 8000:80
  #   environment:
  #     - MICRM_DB_ADDRESS=db-msk
  #     - SUBSCRIPTION_DB=db
  #     - SHOULD_INIT_DB=false
  #   depends_on:
  #     - db
  #     - app
  #     - db-msk

  # db-msk:
  #   container_name: micrm-db-msk
  #   image: micrm-db
  #   ports:
  #     - 5433:5432
  #   command: ["-c", "wal_level=logical", "-c", "max_connections=500"]

# # MODELLING DISTRIBUTED SYSTEM (CREATING SYSTEM IN SPB REGION)
#   app-spb:
#     container_name: micrm-app-spb
#     image: rienelmot24/micrm-app
#     ports:
#       - 8080:80
#     environment:
#       - MICRM_DB_ADDRESS=db-spb
#     depends_on:
#       - db-spb
#
#   db-spb:
#     container_name: micrm-db-spb
#     image: rienelmot24/micrm-db
#     ports:
#       - 5434:5432