CREATE TABLE "__EFMigrationsHistory"
(
    "MigrationId"    VARCHAR(150) NOT NULL
        CONSTRAINT "PK___EFMigrationsHistory"
            PRIMARY KEY,
    "ProductVersion" VARCHAR(32)  NOT NULL
);

ALTER TABLE "__EFMigrationsHistory"
    OWNER TO admin;

CREATE TABLE "Address"
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Address"
            PRIMARY KEY,
    full_address TEXT
);

ALTER TABLE "Address"
    OWNER TO admin;

CREATE TABLE "AspNetRoles"
(
    "Id"               TEXT NOT NULL
        CONSTRAINT "PK_AspNetRoles"
            PRIMARY KEY,
    "Name"             VARCHAR(256),
    "NormalizedName"   VARCHAR(256),
    "ConcurrencyStamp" TEXT
);

ALTER TABLE "AspNetRoles"
    OWNER TO admin;

CREATE UNIQUE INDEX "RoleNameIndex"
    ON "AspNetRoles" ("NormalizedName");

CREATE TABLE "AspNetUsers"
(
    "Id"                   TEXT    NOT NULL
        CONSTRAINT "PK_AspNetUsers"
            PRIMARY KEY,
    "UserName"             VARCHAR(256),
    "NormalizedUserName"   VARCHAR(256),
    "Email"                VARCHAR(256),
    "NormalizedEmail"      VARCHAR(256),
    "EmailConfirmed"       BOOLEAN NOT NULL,
    "PasswordHash"         TEXT,
    "SecurityStamp"        TEXT,
    "ConcurrencyStamp"     TEXT,
    "PhoneNumber"          TEXT,
    "PhoneNumberConfirmed" BOOLEAN NOT NULL,
    "TwoFactorEnabled"     BOOLEAN NOT NULL,
    "LockoutEnd"           TIMESTAMP WITH TIME ZONE,
    "LockoutEnabled"       BOOLEAN NOT NULL,
    "AccessFailedCount"    INTEGER NOT NULL,
    "MyId"                 INTEGER NOT NULL
);

ALTER TABLE "AspNetUsers"
    OWNER TO admin;

CREATE INDEX "EmailIndex"
    ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex"
    ON "AspNetUsers" ("NormalizedUserName");

CREATE TABLE "Country"
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Country"
            PRIMARY KEY,
    name TEXT
);

ALTER TABLE "Country"
    OWNER TO admin;

CREATE TABLE "DeviceCodes"
(
    "UserCode"     VARCHAR(200)   NOT NULL
        CONSTRAINT "PK_DeviceCodes"
            PRIMARY KEY,
    "DeviceCode"   VARCHAR(200)   NOT NULL,
    "SubjectId"    VARCHAR(200),
    "ClientId"     VARCHAR(200)   NOT NULL,
    "CreationTime" TIMESTAMP      NOT NULL,
    "Expiration"   TIMESTAMP      NOT NULL,
    "Data"         VARCHAR(50000) NOT NULL
);

ALTER TABLE "DeviceCodes"
    OWNER TO admin;

CREATE UNIQUE INDEX "IX_DeviceCodes_DeviceCode"
    ON "DeviceCodes" ("DeviceCode");

CREATE INDEX "IX_DeviceCodes_Expiration"
    ON "DeviceCodes" ("Expiration");

CREATE TABLE "GoodType"
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_GoodType"
            PRIMARY KEY,
    type_name TEXT
);

ALTER TABLE "GoodType"
    OWNER TO admin;

CREATE TABLE "PersistedGrants"
(
    "Key"          VARCHAR(200)   NOT NULL
        CONSTRAINT "PK_PersistedGrants"
            PRIMARY KEY,
    "Type"         VARCHAR(50)    NOT NULL,
    "SubjectId"    VARCHAR(200),
    "ClientId"     VARCHAR(200)   NOT NULL,
    "CreationTime" TIMESTAMP      NOT NULL,
    "Expiration"   TIMESTAMP,
    "Data"         VARCHAR(50000) NOT NULL
);

ALTER TABLE "PersistedGrants"
    OWNER TO admin;

CREATE INDEX "IX_PersistedGrants_Expiration"
    ON "PersistedGrants" ("Expiration");

CREATE INDEX "IX_PersistedGrants_SubjectId_ClientId_Type"
    ON "PersistedGrants" ("SubjectId", "ClientId", "Type");

CREATE TABLE "Factory"
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Factory"
            PRIMARY KEY,
    name            TEXT,
    address         INTEGER
        CONSTRAINT "FK_Factory_Address_address"
            REFERENCES "Address"
            ON DELETE RESTRICT,
    foundation_date TIMESTAMP NOT NULL
);

ALTER TABLE "Factory"
    OWNER TO admin;

CREATE INDEX "IX_Factory_address"
    ON "Factory" (address);

CREATE TABLE "Store"
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Store"
            PRIMARY KEY,
    name            TEXT,
    address         INTEGER
        CONSTRAINT "FK_Store_Address_address"
            REFERENCES "Address"
            ON DELETE RESTRICT,
    foundation_date TIMESTAMP NOT NULL
);

ALTER TABLE "Store"
    OWNER TO admin;

CREATE INDEX "IX_Store_address"
    ON "Store" (address);

CREATE TABLE "AspNetRoleClaims"
(
    "Id"         INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_AspNetRoleClaims"
            PRIMARY KEY,
    "RoleId"     TEXT NOT NULL
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
            REFERENCES "AspNetRoles"
            ON DELETE CASCADE,
    "ClaimType"  TEXT,
    "ClaimValue" TEXT
);

ALTER TABLE "AspNetRoleClaims"
    OWNER TO admin;

CREATE INDEX "IX_AspNetRoleClaims_RoleId"
    ON "AspNetRoleClaims" ("RoleId");

CREATE TABLE "AspNetUserClaims"
(
    "Id"         INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_AspNetUserClaims"
            PRIMARY KEY,
    "UserId"     TEXT NOT NULL
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
            REFERENCES "AspNetUsers"
            ON DELETE CASCADE,
    "ClaimType"  TEXT,
    "ClaimValue" TEXT
);

ALTER TABLE "AspNetUserClaims"
    OWNER TO admin;

CREATE INDEX "IX_AspNetUserClaims_UserId"
    ON "AspNetUserClaims" ("UserId");

CREATE TABLE "AspNetUserLogins"
(
    "LoginProvider"       VARCHAR(128) NOT NULL,
    "ProviderKey"         VARCHAR(128) NOT NULL,
    "ProviderDisplayName" TEXT,
    "UserId"              TEXT         NOT NULL
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
            REFERENCES "AspNetUsers"
            ON DELETE CASCADE,
    CONSTRAINT "PK_AspNetUserLogins"
        PRIMARY KEY ("LoginProvider", "ProviderKey")
);

ALTER TABLE "AspNetUserLogins"
    OWNER TO admin;

CREATE INDEX "IX_AspNetUserLogins_UserId"
    ON "AspNetUserLogins" ("UserId");

CREATE TABLE "AspNetUserRoles"
(
    "UserId" TEXT NOT NULL
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
            REFERENCES "AspNetUsers"
            ON DELETE CASCADE,
    "RoleId" TEXT NOT NULL
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
            REFERENCES "AspNetRoles"
            ON DELETE CASCADE,
    CONSTRAINT "PK_AspNetUserRoles"
        PRIMARY KEY ("UserId", "RoleId")
);

ALTER TABLE "AspNetUserRoles"
    OWNER TO admin;

CREATE INDEX "IX_AspNetUserRoles_RoleId"
    ON "AspNetUserRoles" ("RoleId");

CREATE TABLE "AspNetUserTokens"
(
    "UserId"        TEXT         NOT NULL
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
            REFERENCES "AspNetUsers"
            ON DELETE CASCADE,
    "LoginProvider" VARCHAR(128) NOT NULL,
    "Name"          VARCHAR(128) NOT NULL,
    "Value"         TEXT,
    CONSTRAINT "PK_AspNetUserTokens"
        PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

ALTER TABLE "AspNetUserTokens"
    OWNER TO admin;

CREATE TABLE "Buyer"
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Buyer"
            PRIMARY KEY,
    first_name TEXT,
    last_name  TEXT,
    patronymic TEXT,
    email      TEXT,
    phone      TEXT,
    crm_user   TEXT
        CONSTRAINT "FK_Buyer_AspNetUsers_crm_user"
            REFERENCES "AspNetUsers"
            ON DELETE RESTRICT
);

ALTER TABLE "Buyer"
    OWNER TO admin;

CREATE INDEX "IX_Buyer_crm_user"
    ON "Buyer" (crm_user);

CREATE TABLE "Staff"
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Staff"
            PRIMARY KEY,
    first_name      TEXT,
    last_name       TEXT,
    patronymic      TEXT,
    passport_serial TEXT,
    passport_number TEXT,
    phone           TEXT,
    inn             TEXT,
    snils           TEXT,
    crm_user        TEXT
        CONSTRAINT "FK_Staff_AspNetUsers_crm_user"
            REFERENCES "AspNetUsers"
            ON DELETE RESTRICT
);

ALTER TABLE "Staff"
    OWNER TO admin;

CREATE INDEX "IX_Staff_crm_user"
    ON "Staff" (crm_user);

CREATE TABLE "Mark"
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Mark"
            PRIMARY KEY,
    name    TEXT,
    country INTEGER
        CONSTRAINT "FK_Mark_Country_country"
            REFERENCES "Country"
            ON DELETE RESTRICT
);

ALTER TABLE "Mark"
    OWNER TO admin;

CREATE INDEX "IX_Mark_country"
    ON "Mark" (country);

CREATE TABLE "Good"
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Good"
            PRIMARY KEY,
    name        TEXT    NOT NULL,
    description TEXT    NOT NULL,
    good_type   INTEGER
        CONSTRAINT "FK_Good_GoodType_good_type"
            REFERENCES "GoodType"
            ON DELETE RESTRICT,
    factory     INTEGER
        CONSTRAINT "FK_Good_Factory_factory"
            REFERENCES "Factory"
            ON DELETE RESTRICT,
    price       NUMERIC NOT NULL
);

ALTER TABLE "Good"
    OWNER TO admin;

CREATE INDEX "IX_Good_factory"
    ON "Good" (factory);

CREATE INDEX "IX_Good_good_type"
    ON "Good" (good_type);

CREATE TABLE "Model"
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Model"
            PRIMARY KEY,
    model_name TEXT,
    mark       INTEGER
        CONSTRAINT "FK_Model_Mark_mark"
            REFERENCES "Mark"
            ON DELETE RESTRICT,
    year       TIMESTAMP NOT NULL
);

ALTER TABLE "Model"
    OWNER TO admin;

CREATE INDEX "IX_Model_mark"
    ON "Model" (mark);

CREATE TABLE "SupplyInStore"
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_SupplyInStore"
            PRIMARY KEY,
    good  INTEGER
        CONSTRAINT "FK_SupplyInStore_Good_good"
            REFERENCES "Good"
            ON DELETE RESTRICT,
    store INTEGER
        CONSTRAINT "FK_SupplyInStore_Store_store"
            REFERENCES "Store"
            ON DELETE RESTRICT,
    date  TIMESTAMP NOT NULL
);

ALTER TABLE "SupplyInStore"
    OWNER TO admin;

CREATE INDEX "IX_SupplyInStore_good"
    ON "SupplyInStore" (good);

CREATE INDEX "IX_SupplyInStore_store"
    ON "SupplyInStore" (store);

CREATE TABLE "Car"
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Car"
            PRIMARY KEY,
    serial     TEXT,
    region     TEXT,
    mark_model INTEGER
        CONSTRAINT "FK_Car_Model_mark_model"
            REFERENCES "Model"
            ON DELETE RESTRICT
);

ALTER TABLE "Car"
    OWNER TO admin;

CREATE INDEX "IX_Car_mark_model"
    ON "Car" (mark_model);

CREATE TABLE "Delivery"
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Delivery"
            PRIMARY KEY,
    car     INTEGER
        CONSTRAINT "FK_Delivery_Car_car"
            REFERENCES "Car"
            ON DELETE RESTRICT,
    address INTEGER
        CONSTRAINT "FK_Delivery_Address_address"
            REFERENCES "Address"
            ON DELETE RESTRICT,
    courier INTEGER
        CONSTRAINT "FK_Delivery_Staff_courier"
            REFERENCES "Staff"
            ON DELETE RESTRICT
);

ALTER TABLE "Delivery"
    OWNER TO admin;

CREATE INDEX "IX_Delivery_address"
    ON "Delivery" (address);

CREATE INDEX "IX_Delivery_car"
    ON "Delivery" (car);

CREATE INDEX "IX_Delivery_courier"
    ON "Delivery" (courier);

CREATE TABLE "Offer"
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_Offer"
            PRIMARY KEY,
    code     TEXT,
    buyer    INTEGER
        CONSTRAINT "FK_Offer_Buyer_buyer"
            REFERENCES "Buyer"
            ON DELETE RESTRICT,
    seller   INTEGER
        CONSTRAINT "FK_Offer_Staff_seller"
            REFERENCES "Staff"
            ON DELETE RESTRICT,
    store    INTEGER
        CONSTRAINT "FK_Offer_Store_store"
            REFERENCES "Store"
            ON DELETE RESTRICT,
    delivery INTEGER
        CONSTRAINT "FK_Offer_Delivery_delivery"
            REFERENCES "Delivery"
            ON DELETE RESTRICT,
    sum      NUMERIC NOT NULL
);

ALTER TABLE "Offer"
    OWNER TO admin;

CREATE INDEX "IX_Offer_buyer"
    ON "Offer" (buyer);

CREATE INDEX "IX_Offer_delivery"
    ON "Offer" (delivery);

CREATE INDEX "IX_Offer_seller"
    ON "Offer" (seller);

CREATE INDEX "IX_Offer_store"
    ON "Offer" (store);

CREATE TABLE "GoodInOffer"
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_GoodInOffer"
            PRIMARY KEY,
    good  INTEGER
        CONSTRAINT "FK_GoodInOffer_Good_good"
            REFERENCES "Good"
            ON DELETE RESTRICT,
    offer INTEGER
        CONSTRAINT "FK_GoodInOffer_Offer_offer"
            REFERENCES "Offer"
            ON DELETE RESTRICT,
    count INTEGER NOT NULL
);

ALTER TABLE "GoodInOffer"
    OWNER TO admin;

CREATE INDEX "IX_GoodInOffer_good"
    ON "GoodInOffer" (good);

CREATE INDEX "IX_GoodInOffer_offer"
    ON "GoodInOffer" (offer);